name: PIPELINE

on:
  push:
    branches: [ "master" ]

jobs:
  build-docker-image:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "master"

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: anuragdocker218
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build the docker image
        run: |
          #!/bin/bash

          docker build -t anuragdocker218/mahakal:java-api1 .

      - name: push to docker hub
        run: |
          #!/bin/bash

          docker push anuragdocker218/mahakal:java-api1